; Music exported with PokeMini Music Converter v1.1
; Header file

; Title: Galactix Music
; Composer: Original by Lupin
; Programmer: Remix by JustBurn
.set music_galactix_title "Galactix Music"
.set music_galactix_composer "Original by Lupin"
.set music_galactix_programmer "Remix by JustBurn"

; Mastertime: $00FF, (255)
.set music_galactix_mastertime 255

;   4 Pattern(s)
; 'music_galactix_p0'
; 'music_galactix2_p0'
; 'music_galactix_ENDBGM'
; 'music_galactix2_ENDBGM'

;   0 SFX

;   2 BGM
; 'music_galactix'
; 'music_galactix2'

